spring: 
  profiles:
    active:
      - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: cloud-config-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-dev.com:7001/eureka/
---
# server:
#   port: 8205
spring:
  profiles: test
#   application:
#     name: cloud-config-client-aa
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
